import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLocale } from "@/contexts/LocaleContext";
import { trpc } from "@/lib/trpc";
import { KeyRound, ShieldAlert } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function AdminAccessPanel() {
  const { isArabic } = useLocale(); const utils = trpc.useUtils(); const { data: profile } = trpc.auth.localProfile.useQuery();
  const [username, setUsername] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const update = trpc.auth.updateLocalCredentials.useMutation({ onSuccess: () => { toast.success(isArabic ? "تم تحديث بيانات الدخول. أعد تسجيل الدخول عند الحاجة." : "Credentials updated. Sign in again when needed."); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); void utils.auth.localProfile.invalidate(); }, onError: error => toast.error(error.message || (isArabic ? "تعذر تحديث البيانات" : "Credentials could not be updated")) });
  function submit(event: FormEvent) { event.preventDefault(); if (newPassword !== confirmPassword) { toast.error(isArabic ? "تأكيد كلمة المرور غير متطابق." : "The password confirmation does not match."); return; } update.mutate({ username: username || profile?.username || "admin", currentPassword, password: newPassword }); }
  return <div className="mx-auto max-w-3xl"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#e5f3f4] text-[#16717d]"><KeyRound className="h-5 w-5" /></div><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#1b7b86]">{isArabic ? "الأمان" : "SECURITY"}</p><h1 className="mt-1 font-display text-3xl text-[#17323b]">{isArabic ? "بيانات دخول المدير" : "Administrator credentials"}</h1><p className="mt-2 text-sm leading-7 text-[#617a80]">{isArabic ? "يجب تحديث بيانات الدخول المؤقتة قبل النشر، وعدم مشاركة كلمة المرور مع غير المخولين." : "Change temporary credentials before publishing and do not share the password with unauthorized people."}</p></div></div><div className="mt-7 rounded-2xl border border-[#f0d9aa] bg-[#fff8e8] p-4 text-sm leading-7 text-[#7c5a1f]"><div className="flex gap-2"><ShieldAlert className="mt-1 h-4 w-4 shrink-0" /><p>{isArabic ? "الحساب الحالي مؤقت للاختبار. استخدم كلمة مرور جديدة من 8 أحرف على الأقل قبل نشر الموقع." : "The current account is for testing. Use a new password of at least 8 characters before publishing."}</p></div></div><form onSubmit={submit} className="mt-6 rounded-3xl border border-[#dbe7e9] bg-white p-6"><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-2 block text-xs font-bold text-[#617a80]">{isArabic ? "اسم المستخدم الحالي" : "Current username"}</label><Input value={profile?.username || "..."} readOnly className="bg-[#f8f6f0]" /></div><div><label className="mb-2 block text-xs font-bold text-[#617a80]">{isArabic ? "اسم المستخدم الجديد" : "New username"}</label><Input value={username} onChange={event => setUsername(event.target.value.replace(/[^a-zA-Z0-9._-]/g, ""))} placeholder={profile?.username || "admin"} /></div><div className="sm:col-span-2"><label className="mb-2 block text-xs font-bold text-[#617a80]">{isArabic ? "كلمة المرور الحالية" : "Current password"}</label><Input required type="password" autoComplete="current-password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} /></div><div><label className="mb-2 block text-xs font-bold text-[#617a80]">{isArabic ? "كلمة المرور الجديدة" : "New password"}</label><Input required minLength={8} type="password" autoComplete="new-password" value={newPassword} onChange={event => setNewPassword(event.target.value)} /></div><div><label className="mb-2 block text-xs font-bold text-[#617a80]">{isArabic ? "تأكيد كلمة المرور الجديدة" : "Confirm new password"}</label><Input required minLength={8} type="password" autoComplete="new-password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} /></div></div><Button type="submit" disabled={update.isPending} className="mt-6 h-11 w-full rounded-md bg-[#16717d] hover:bg-[#105d67]">{update.isPending ? (isArabic ? "جارٍ الحفظ..." : "Saving...") : (isArabic ? "حفظ بيانات الدخول الجديدة" : "Save new credentials")}</Button></form></div>;
}
