import StoreShell from "@/components/StoreShell";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { useContactInfo } from "@/hooks/useContactInfo";
import { Clock3, Instagram, MapPin, MessageCircleMore, Phone } from "lucide-react";

export default function Contact() {
  const { isArabic } = useLocale(); const contact = useContactInfo(); const cards = [{ icon: MapPin, title: isArabic ? "موقعنا" : "Our location", text: isArabic ? contact.addressAr : contact.addressEn }, { icon: Phone, title: isArabic ? "الهاتف والواتساب" : "Phone & WhatsApp", text: contact.phone }, { icon: Clock3, title: isArabic ? "خدمة التوصيل" : "Delivery", text: isArabic ? "متاحة لجميع إمارات الدولة" : "Available across the UAE" }];
  return <StoreShell><section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-[2rem] bg-[#24233a] p-8 text-white sm:p-12"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#dcb65c]">{isArabic ? "دعنا نبدأ" : "LET'S START"}</p><h1 className="mt-4 max-w-lg font-display text-4xl leading-tight sm:text-6xl">{isArabic ? "فكرتك تستحق أن تصبح هدية لا تُنسى" : "Your idea deserves to become an unforgettable gift"}</h1><p className="mt-6 max-w-lg text-sm leading-8 text-[#d9d0ca] sm:text-base">{isArabic ? "أرسلي فكرتك أو تفاصيل المناسبة والكمية، وسنتواصل معك لتجهيز أفضل خيار مناسب." : "Send your idea, occasion details and quantity, and we’ll help you shape the right option."}</p><Button asChild className="mt-8 h-12 rounded-xl bg-[#dcb65c] px-6 font-bold text-[#24233a] hover:bg-[#efca72]"><a href={contact.whatsappUrl} target="_blank" rel="noreferrer"><MessageCircleMore />{isArabic ? "مراسلتنا عبر واتساب" : "Message us on WhatsApp"}</a></Button></div><div className="grid gap-4">{cards.map(card => <article key={card.title} className="flex items-start gap-4 rounded-3xl border border-[#e9e3d6] bg-white p-6"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#f0eaf5] text-[#7953a2]"><card.icon className="h-5 w-5" /></div><div><h2 className="font-display text-xl text-[#24233a]">{card.title}</h2><p className="mt-1 text-sm leading-6 text-[#766f69]">{card.text}</p></div></article>)}<a href={contact.instagramUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-3xl bg-[#7953a2] px-6 py-5 text-white transition hover:bg-[#654287]"><Instagram className="h-5 w-5" /><span className="font-bold">@{contact.instagram.replace(/^@/, "")}</span><span className="ms-auto text-sm opacity-80">{isArabic ? "شاهدي أعمالنا" : "See our work"}</span></a></div></div></section></StoreShell>;
}
