import ProductCard from "@/components/ProductCard";
import StoreShell from "@/components/StoreShell";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { useContactInfo } from "@/hooks/useContactInfo";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowUpLeft, Award, Boxes, Gift, LayoutPanelTop, Package, Paintbrush, Sparkles, Stamp, Tag, Truck, type LucideIcon } from "lucide-react";
import { Link } from "wouter";

const FALLBACK_HERO_IMAGE = "/manus-storage/social-2_de273aa2.jpg";
const FALLBACK_PROMO_IMAGE = "/manus-storage/social-3_0108449b.jpg";
type HomeCategory = { slug: string; ar: string; en: string; Icon: LucideIcon };
const fallbackCategories: HomeCategory[] = [
  { slug: "promotional-gifts", Icon: Gift, ar: "هدايا إعلانية", en: "Promo gifts" },
  { slug: "occasion-stationery", Icon: Stamp, ar: "بطاقات ومناسبات", en: "Occasions" },
  { slug: "boxes-packaging", Icon: Boxes, ar: "بوكسات", en: "Boxes" },
  { slug: "custom-printing", Icon: Paintbrush, ar: "طباعة حسب الطلب", en: "Custom print" },
  { slug: "stands-boards", Icon: LayoutPanelTop, ar: "لوحات وستاندات", en: "Boards & stands" },
  { slug: "engraving-details", Icon: Sparkles, ar: "حفر وتفاصيل", en: "Engraving" },
];
const categoryIcons: Record<string, LucideIcon> = { Gift, Stamp, Boxes, Paintbrush, LayoutPanelTop, Sparkles };

function SectionTitle({ eyebrow, title, href = "/shop", action }: { eyebrow: string; title: string; href?: string; action: string }) {
  return <div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#8c719c]">{eyebrow}</p><h2 className="mt-2 font-display text-2xl text-[#24233a] sm:text-3xl">{title}</h2></div><Link href={href} className="inline-flex shrink-0 items-center gap-1 text-sm font-bold text-[#7953a2] hover:text-[#5e3c80]">{action}<ArrowUpLeft className="h-4 w-4" /></Link></div>;
}

export default function Home() {
  const { isArabic } = useLocale();
  const contact = useContactInfo();
  const queryOptions = { refetchInterval: 30_000, refetchOnWindowFocus: true };
  const { data: products = [], isLoading } = trpc.store.catalog.products.useQuery(undefined, queryOptions);
  const { data: siteCategories = [] } = trpc.store.catalog.categories.useQuery(undefined, queryOptions);
  const { data: homeContent } = trpc.store.catalog.homeContent.useQuery(undefined, queryOptions);
  const heroImage = homeContent?.heroImage || FALLBACK_HERO_IMAGE;
  const promoImage = homeContent?.promoImage || FALLBACK_PROMO_IMAGE;
  const title = isArabic ? homeContent?.heroTitleAr || "مطبوعات وهدايا تليق بتفاصيلك" : homeContent?.heroTitleEn || "Printing and gifts made for your details";
  const subtitle = isArabic ? homeContent?.heroSubtitleAr || "استكشفي تشكيلات الهدايا، المطبوعات، البوكسات واللوحات، واحتفظي بما يعجبك في سلة طلب واحدة." : homeContent?.heroSubtitleEn || "Explore gifts, print pieces, boxes and boards, then collect your selections in one request cart.";
  const displayCategories: HomeCategory[] = siteCategories.length ? siteCategories.map(category => ({ slug: category.slug, ar: category.titleAr, en: category.titleEn, Icon: categoryIcons[category.icon] || Sparkles })) : fallbackCategories;

  return <StoreShell>
    <section className="border-b border-[#e9e3d6] bg-[#faf8fb]"><div className="mx-auto max-w-[1440px] px-4 py-4 sm:px-8"><div className="relative grid min-h-[360px] overflow-hidden rounded-2xl bg-[#eee5f3] lg:grid-cols-[1.08fr_.92fr]"><div className="absolute -left-24 -top-28 h-72 w-72 rounded-full bg-[#dcb65c]/35 blur-3xl" /><div className="relative order-2 flex flex-col justify-center p-8 sm:p-12 lg:order-1 lg:p-16"><span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#d5c4df] bg-white/70 px-3 py-1.5 text-xs font-bold text-[#7953a2]"><Tag className="h-3.5 w-3.5" />{isArabic ? "تصاميم حسب الطلب" : "MADE TO ORDER"}</span><h1 className="mt-5 max-w-2xl font-display text-4xl leading-tight text-[#24233a] sm:text-6xl">{title}</h1><p className="mt-5 max-w-xl text-sm leading-7 text-[#6c6562] sm:text-base">{subtitle}</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild className="h-11 rounded-lg bg-[#7953a2] px-5 hover:bg-[#654287]"><Link href="/shop">{isArabic ? "تصفحي المنتجات" : "Browse products"}<ArrowLeft className="h-4 w-4" /></Link></Button><Button asChild variant="outline" className="h-11 rounded-lg border-[#cdbbd6] bg-white/70 px-5 text-[#5e3c80] hover:bg-white"><a href={contact.whatsappUrl} target="_blank" rel="noreferrer">{isArabic ? "طلب مخصص" : "Custom request"}</a></Button></div><div className="mt-8 flex flex-wrap gap-5 text-xs font-bold text-[#615a56]"><span className="inline-flex items-center gap-2"><Truck className="h-4 w-4 text-[#7953a2]" />{isArabic ? "توصيل لكل الإمارات" : "UAE-wide delivery"}</span><span className="inline-flex items-center gap-2"><Package className="h-4 w-4 text-[#7953a2]" />{isArabic ? "سلة طلب موحدة" : "One request cart"}</span></div></div><div className="relative order-1 min-h-[280px] p-6 lg:order-2 lg:p-9"><div className="absolute inset-0 bg-[radial-gradient(circle_at_60%_30%,rgba(255,255,255,.85),transparent_45%)]" /><img src={heroImage} alt={isArabic ? "بانر مخصص من مطبعة الروعة" : "Custom banner by Al Rawaa"} className="relative h-full w-full rounded-xl object-cover shadow-[0_25px_50px_-28px_rgba(36,35,58,.75)]" /><span className="absolute bottom-10 start-10 rounded-xl bg-[#24233a] px-4 py-3 text-white shadow-lg"><span className="block text-[10px] font-bold tracking-[.15em] text-[#dcb65c]">{isArabic ? "الأكثر طلبًا" : "POPULAR PICK"}</span><span className="mt-1 block font-display text-lg">{isArabic ? "لوحات التصوير" : "Photo boards"}</span></span></div></div></div></section>
    <section className="border-b border-[#eee9e1] bg-white"><div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-8"><div className="flex items-center justify-between"><h2 className="font-display text-2xl">{isArabic ? "تسوّقي حسب الفئة" : "Shop by category"}</h2><Link href="/shop" className="text-xs font-bold text-[#7953a2]">{isArabic ? "عرض الكل" : "View all"}</Link></div><div className="mt-5 flex gap-3 overflow-x-auto pb-2">{displayCategories.map(category => <Link key={category.slug} href={`/services/${category.slug}`} className="group flex min-w-[138px] flex-1 flex-col items-center gap-3 rounded-xl border border-[#ebe7df] bg-[#fffdf8] px-4 py-5 text-center transition hover:border-[#b99cca] hover:bg-[#f7f3f8] sm:min-w-[155px]"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#f0eaf5] text-[#7953a2] transition group-hover:bg-[#7953a2] group-hover:text-white"><category.Icon className="h-5 w-5" /></span><span className="text-xs font-bold text-[#4f4a46]">{isArabic ? category.ar : category.en}</span></Link>)}</div></div></section>
    <section className="mx-auto grid max-w-[1440px] gap-4 px-4 py-8 sm:px-8 lg:grid-cols-2"><Link href="/services/occasion-stationery" className="group relative min-h-56 overflow-hidden rounded-2xl bg-[#24233a] p-7 text-white"><img src={promoImage} alt="" className="absolute inset-0 h-full w-full object-cover opacity-35 transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-l from-[#24233a]/95 to-[#24233a]/35" /><div className="relative max-w-sm"><p className="text-xs font-black uppercase tracking-[.2em] text-[#dcb65c]">{isArabic ? "مناسباتك" : "OCCASIONS"}</p><h2 className="mt-3 font-display text-3xl">{isArabic ? "اطبعي فرحتك بطابعك" : "Print your celebration your way"}</h2><span className="mt-6 inline-flex items-center gap-1 text-sm font-bold">{isArabic ? "اكتشفي التفاصيل" : "Discover details"}<ArrowUpLeft className="h-4 w-4" /></span></div></Link><Link href="/services/boxes-packaging" className="group relative min-h-56 overflow-hidden rounded-2xl bg-[#dcb65c] p-7 text-[#24233a]"><div className="absolute -bottom-20 -end-12 h-64 w-64 rounded-full border-[24px] border-white/45" /><div className="relative max-w-sm"><p className="text-xs font-black uppercase tracking-[.2em] text-[#6a4a23]">{isArabic ? "تغليف وهدايا" : "PACKAGING"}</p><h2 className="mt-3 font-display text-3xl">{isArabic ? "بوكسات تُكمل شكل الهدية" : "Boxes that complete the gift"}</h2><span className="mt-6 inline-flex items-center gap-1 text-sm font-bold">{isArabic ? "عرض البوكسات" : "View boxes"}<ArrowUpLeft className="h-4 w-4" /></span></div></Link></section>
    <section className="mx-auto max-w-[1440px] px-4 py-10 sm:px-8"><SectionTitle eyebrow={isArabic ? "مختارات الروعة" : "AL RAWAA PICKS"} title={isArabic ? "منتجات جاهزة لتُضاف لطلبك" : "Products ready for your request"} action={isArabic ? "عرض الكل" : "View all"} />{isLoading ? <div className="mt-7 grid grid-cols-2 gap-4 lg:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-72 animate-pulse rounded-xl bg-[#f4f0f6]" />)}</div> : products.length ? <div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{products.slice(0, 8).map(product => <ProductCard key={product.product.id} product={product} />)}</div> : <div className="mt-7 rounded-2xl border border-dashed border-[#d6c9dd] bg-[#faf8fb] p-8 text-center"><Award className="mx-auto h-7 w-7 text-[#7953a2]" /><p className="mt-3 text-sm text-[#766f69]">{isArabic ? "لا توجد منتجات منشورة بعد. أرسلي فكرتك وسنحوّلها إلى طلب خاص." : "There are no published products yet. Share your idea and we will turn it into a custom request."}</p></div>}</section>
    <section className="border-y border-[#eee9e1] bg-[#faf8fb]"><div className="mx-auto max-w-[1440px] px-4 py-10 sm:px-8"><SectionTitle eyebrow={isArabic ? "كيف يتم الطلب؟" : "HOW IT WORKS"} title={isArabic ? "اختاري، أضيفي، ثم أرسلي" : "Choose, add, then send"} href="/shop" action={isArabic ? "ابدئي التسوق" : "Start shopping"} /><div className="mt-7 grid gap-4 md:grid-cols-3">{(isArabic ? [["1", "تصفحي الفئات", "ابحثي عن المنتج أو الخدمة المناسبة."], ["2", "أضيفي إلى سلة الطلب", "اجمعي كل اختياراتك في مكان واحد."], ["3", "أرسلي التفاصيل", "نحفظ الطلب ونفتح واتساب للتأكيد."]] : [["1", "Browse categories", "Find the product or service that suits you."], ["2", "Add to request cart", "Collect your selections in one place."], ["3", "Send the details", "We save your request then open WhatsApp to confirm."]]).map(([number, heading, copy]) => <article key={number} className="rounded-xl border border-[#e9e3d6] bg-white p-5"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#7953a2] text-xs font-black text-white">{number}</span><h3 className="mt-4 font-display text-2xl">{heading}</h3><p className="mt-2 text-sm leading-6 text-[#766f69]">{copy}</p></article>)}</div></div></section>
  </StoreShell>;
}
