import OrderForm from "@/components/OrderForm";
import StoreShell from "@/components/StoreShell";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { formatMoney } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Check, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { Link, useRoute } from "wouter";

const FALLBACK_IMAGE = "/manus-storage/social-1_e277342a.jpg";

export default function ProductDetail() {
  const [, params] = useRoute("/products/:handle");
  const handle = params?.handle ?? "";
  const { data: record, isLoading, error, refetch } = trpc.store.catalog.productBySlug.useQuery({ slug: handle }, { enabled: Boolean(handle), staleTime: 5 * 60 * 1000, refetchOnWindowFocus: false });
  const { isArabic, locale, direction } = useLocale();

  if (isLoading) return <StoreShell><section aria-busy="true" className="raed-container grid gap-10 py-12 lg:grid-cols-2 lg:py-16"><div><div className="mb-5 h-5 w-32 animate-pulse rounded bg-[#e5f3f4]" /><div className="aspect-square animate-pulse rounded-md bg-[#e5f3f4]" /></div><div className="self-center"><div className="h-4 w-28 animate-pulse rounded bg-[#e5f3f4]" /><div className="mt-4 h-14 max-w-lg animate-pulse rounded bg-[#e5f3f4]" /><div className="mt-6 h-5 w-24 animate-pulse rounded bg-[#e5f3f4]" /><div className="mt-6 space-y-3"><div className="h-4 max-w-xl animate-pulse rounded bg-[#e5f3f4]" /><div className="h-4 max-w-lg animate-pulse rounded bg-[#e5f3f4]" /></div><div className="mt-8 h-32 animate-pulse rounded-md bg-[#e5f3f4]" /></div></section></StoreShell>;
  if (error) return <StoreShell><div role="alert" className="raed-container grid min-h-[60vh] max-w-xl place-items-center text-center"><div><h1 className="font-display text-3xl">{isArabic ? "تعذر تحميل المنتج" : "This product could not be loaded"}</h1><p className="mt-3 text-sm leading-7 text-[#617a80]">{isArabic ? "تحققي من الاتصال وحاولي مرة أخرى." : "Check your connection and try again."}</p><div className="mt-5 flex justify-center gap-3"><Button onClick={() => refetch()} variant="outline" className="rounded-md border-[#a8cdd1]">{isArabic ? "إعادة المحاولة" : "Retry"}</Button><Button asChild className="rounded-md bg-[#16717d]"><Link href="/shop">{isArabic ? "العودة للمتجر" : "Back to shop"}</Link></Button></div></div></div></StoreShell>;
  if (!record) return <StoreShell><div className="raed-container grid min-h-[60vh] max-w-xl place-items-center text-center"><div><h1 className="font-display text-3xl">{isArabic ? "لم نجد هذا المنتج" : "We couldn't find this product"}</h1><Button asChild className="mt-5 rounded-md bg-[#16717d]"><Link href="/shop">{isArabic ? "العودة للمتجر" : "Back to shop"}</Link></Button></div></div></StoreShell>;

  const product = record.product;
  const title = isArabic ? product.titleAr : product.titleEn;
  const description = isArabic ? product.descriptionAr : product.descriptionEn;
  return <StoreShell><section className="border-b border-[#e3ebed] bg-[#f6fafb]"><div className="raed-container py-4"><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-bold text-[#12616c]"><ArrowRight className={`h-4 w-4 ${direction === "ltr" ? "rotate-180" : ""}`} />{isArabic ? "العودة إلى المتجر" : "Back to shop"}</Link></div></section><section className="raed-container grid gap-10 py-10 lg:grid-cols-[1.05fr_.95fr] lg:py-16"><div className="overflow-hidden rounded-md border border-[#dbe7e9] bg-white"><img src={product.imageUrl ?? FALLBACK_IMAGE} alt={title} width={960} height={960} decoding="async" fetchPriority="high" className="aspect-square h-full w-full object-cover" /></div><div className="self-center"><p className="raed-kicker">{isArabic ? record.categoryTitleAr : record.categoryTitleEn}</p><h1 className="mt-3 font-display text-4xl leading-tight text-[#17323b] sm:text-5xl">{title}</h1>{product.price ? <strong className="mt-5 block text-2xl text-[#12616c]">{formatMoney(product.price, locale)}</strong> : <span className="mt-5 block text-sm font-bold text-[#12616c]">{isArabic ? "السعر حسب التفاصيل المطلوبة" : "Pricing depends on your requested details"}</span>}<p className="mt-6 whitespace-pre-line text-sm leading-8 text-[#617a80]">{description || (isArabic ? "منتج مميز يمكن تخصيصه وفق تفاصيل مناسبتك." : "A signature piece that can be customised around your occasion.")}</p><div className="mt-7 grid gap-3 border-y border-[#e4edef] py-5 sm:grid-cols-3"><span className="flex items-center gap-2 text-xs font-bold text-[#45656b]"><Truck className="h-4 w-4 text-[#16717d]" />{isArabic ? "توصيل للإمارات" : "UAE delivery"}</span><span className="flex items-center gap-2 text-xs font-bold text-[#45656b]"><Sparkles className="h-4 w-4 text-[#16717d]" />{isArabic ? "تفاصيل حسب الطلب" : "Made to order"}</span><span className="flex items-center gap-2 text-xs font-bold text-[#45656b]"><ShieldCheck className="h-4 w-4 text-[#16717d]" />{isArabic ? "تنفيذ بعناية" : "Made with care"}</span></div><div className="mt-8"><OrderForm product={product} /></div></div></section><section className="raed-section-muted"><div className="raed-container flex flex-wrap items-center justify-between gap-4 py-6 text-sm text-[#5b747a]"><span className="inline-flex items-center gap-2 font-bold"><Check className="h-4 w-4 text-[#16717d]" />{isArabic ? "نراجع كل تفاصيل طلبك قبل البدء" : "We review every detail before production"}</span><span>{isArabic ? "للطلبات الخاصة، تواصلي معنا مباشرة" : "For special requests, contact us directly"}</span></div></section></StoreShell>;
}
