import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { useRequestCart } from "@/contexts/RequestCartContext";
import { useContactInfo } from "@/hooks/useContactInfo";
import { Heart, Instagram, Languages, MapPin, Menu, Phone, Search, ShoppingBag, UserCircle2, X } from "lucide-react";
import { FormEvent, lazy, ReactNode, Suspense, useState } from "react";
import { Link, useLocation } from "wouter";

const FALLBACK_LOGO_URL = "/manus-storage/social-1_e277342a.jpg";
const RequestCartDrawer = lazy(() => import("@/components/RequestCartDrawer"));
const navItems = [
  { href: "/shop?category=promotional-gifts", ar: "هدايا إعلانية", en: "Promotional gifts" },
  { href: "/shop?category=occasion-stationery", ar: "مطبوعات المناسبات", en: "Occasion print" },
  { href: "/shop?category=boxes-packaging", ar: "بوكسات وتغليف", en: "Boxes & packaging" },
  { href: "/shop?category=custom-printing", ar: "طباعة حسب الطلب", en: "Custom printing" },
  { href: "/shop?category=stickers-labels", ar: "ستيكرات وليبلات", en: "Stickers & labels" },
  { href: "/shop?category=paper-bags", ar: "أكياس ورقية", en: "Paper bags" },
  { href: "/shop?category=stands-boards", ar: "ستاندات ولوحات", en: "Stands & boards" },
];

export default function StoreShell({ children, logoUrl }: { children: ReactNode; logoUrl?: string | null }) {
  const { isArabic, toggleLocale } = useLocale();
  const contact = useContactInfo();
  const { totalItems, openCart } = useRequestCart();
  const [menuOpen, setMenuOpen] = useState(false);
  const [mobileSearchOpen, setMobileSearchOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [, setLocation] = useLocation();
  const address = isArabic ? contact.addressAr : contact.addressEn;
  const resolvedLogoUrl = logoUrl || FALLBACK_LOGO_URL;

  function searchSubmit(event: FormEvent) {
    event.preventDefault();
    setMobileSearchOpen(false);
    setLocation(`/shop?search=${encodeURIComponent(search.trim())}`);
  }

  return <div className="min-h-screen overflow-x-hidden bg-[#fff] text-[#17323b]">
    <div className="bg-[#102f39] px-4 py-2 text-[10px] text-[#edf8f8] sm:px-8 sm:text-[11px]"><div className="raed-container flex items-center justify-between gap-3 px-0"><span className="hidden items-center gap-1.5 md:inline-flex"><MapPin className="h-3.5 w-3.5 text-[#f1ba63]" />{address}</span><div className="flex items-center gap-3 sm:gap-4"><a href="/contact" className="hover:text-[#f1ba63]">{isArabic ? "سياسة الطلب" : "Ordering policy"}</a><a href={contact.whatsappUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 hover:text-[#f1ba63]"><Phone className="h-3.5 w-3.5" />{contact.phone}</a></div><button onClick={toggleLocale} className="inline-flex items-center gap-1 font-bold hover:text-[#f1ba63]"><Languages className="h-3.5 w-3.5" />{isArabic ? "English" : "العربية"}</button></div></div>

    <header className="relative z-50 border-b border-[#e3ebed] bg-white/95 shadow-[0_8px_22px_-20px_rgba(16,47,57,.6)] backdrop-blur"><div className="raed-container flex min-h-[68px] items-center gap-2 py-2.5 sm:min-h-[76px] sm:gap-3 sm:py-3"><Link href="/" className="flex shrink-0 items-center gap-2.5"><img src={resolvedLogoUrl} alt={isArabic ? "شعار مطبعة الروعة" : "Al Rawaa Printing logo"} className="h-10 w-10 rounded-xl object-cover ring-1 ring-[#dbe8ea] sm:h-11 sm:w-11" /><div className="hidden leading-tight sm:block"><span className="block font-display text-lg font-bold text-[#14323a]">{isArabic ? "مطبعة الروعة" : "Al Rawaa Printing"}</span><span className="block text-[9px] font-bold uppercase tracking-[.14em] text-[#27818a]">{isArabic ? "هدايا بطابعك" : "Gifts, your way"}</span></div></Link><form onSubmit={searchSubmit} className="hidden flex-1 lg:block"><label className="relative mx-auto block max-w-2xl"><Search className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#8aa0a5]" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder={isArabic ? "ابحث عن هدية أو مطبوعة..." : "Search gifts and printing..."} className="h-11 w-full rounded-full border border-[#d8e4e6] bg-[#f8fbfb] px-11 text-sm outline-none transition focus:border-[#27818a] focus:bg-white focus:shadow-[0_0_0_4px_rgba(39,129,138,.08)]" /></label></form><div className="ms-auto flex items-center gap-1 sm:gap-1.5"><Link href="/admin" className="hidden h-10 items-center gap-1.5 rounded-xl px-2.5 text-xs font-bold text-[#577077] hover:bg-[#eff7f7] sm:inline-flex"><UserCircle2 className="h-5 w-5" />{isArabic ? "حسابي" : "Account"}</Link><button className="hidden h-10 w-10 place-items-center rounded-xl text-[#577077] hover:bg-[#eff7f7] sm:grid" aria-label={isArabic ? "المفضلة" : "Wishlist"}><Heart className="h-5 w-5" /></button><button onClick={() => setMobileSearchOpen(open => !open)} className={`grid h-10 w-10 place-items-center rounded-xl transition lg:hidden ${mobileSearchOpen ? "bg-[#e7f3f4] text-[#12616c]" : "text-[#577077] hover:bg-[#eff7f7]"}`} aria-label={isArabic ? "البحث" : "Search"}><Search className="h-5 w-5" /></button><button onClick={openCart} className="relative inline-flex h-10 items-center gap-2 rounded-xl bg-[#16717d] px-3 text-xs font-bold text-white shadow-[0_10px_20px_-14px_rgba(16,113,125,.9)] transition hover:bg-[#105d67]"><ShoppingBag className="h-4 w-4" /><span className="hidden sm:inline">{isArabic ? "سلة الطلب" : "Cart"}</span>{totalItems ? <span className="grid h-5 min-w-5 place-items-center rounded-full bg-[#f2bd66] px-1 text-[10px] text-[#17323b]">{totalItems}</span> : null}</button><button onClick={() => setMenuOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl border border-[#d8e4e6] bg-white text-[#17323b] lg:hidden" aria-label={isArabic ? "فتح القائمة" : "Open menu"}><Menu className="h-5 w-5" /></button></div></div>
      {mobileSearchOpen ? <form onSubmit={searchSubmit} className="border-t border-[#edf1f2] bg-[#f8fbfb] lg:hidden"><div className="raed-container flex gap-2 py-3"><label className="relative min-w-0 flex-1"><Search className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#8aa0a5]" /><input autoFocus value={search} onChange={event => setSearch(event.target.value)} placeholder={isArabic ? "ابحث في المتجر" : "Search the store"} className="h-11 w-full rounded-xl border border-[#d8e4e6] bg-white px-9 text-sm outline-none focus:border-[#27818a]" /></label><Button type="submit" className="h-11 rounded-xl bg-[#16717d] px-4 hover:bg-[#105d67]">{isArabic ? "بحث" : "Search"}</Button></div></form> : null}
      <nav className="hidden border-t border-[#edf1f2] bg-[#f7fafb] lg:block"><div className="raed-container flex items-center justify-center gap-1 overflow-x-auto px-0"><Link href="/shop" className="border-b-2 border-[#16717d] px-5 py-3 text-sm font-black text-[#12616c]">{isArabic ? "كل المنتجات" : "All products"}</Link>{navItems.map(item => <Link key={item.href} href={item.href} className="shrink-0 px-4 py-3 text-sm font-bold text-[#4b656c] transition hover:bg-white hover:text-[#12616c]">{isArabic ? item.ar : item.en}</Link>)}</div></nav>
    </header>

    {menuOpen ? <div className="fixed inset-0 z-[70] bg-[#0b2d35]/50 p-3 backdrop-blur-sm lg:hidden"><div className="mx-auto flex max-h-full max-w-md flex-col overflow-y-auto rounded-[1.35rem] bg-white p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-[#e1ebed] pb-4"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#27818a]">{isArabic ? "الروعة للهدايا" : "AL RAWAA GIFTS"}</p><span className="mt-1 block font-display text-xl">{isArabic ? "تصفح المتجر" : "Browse store"}</span></div><button onClick={() => setMenuOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-[#e9f4f4] text-[#12616c]"><X className="h-5 w-5" /></button></div><form onSubmit={event => { searchSubmit(event); setMenuOpen(false); }} className="relative mt-5"><Search className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#8aa0a5]" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder={isArabic ? "ابحث في المتجر" : "Search the store"} className="h-11 w-full rounded-xl border border-[#d8e4e6] bg-[#f8fbfb] px-10 text-sm outline-none focus:border-[#27818a]" /></form><nav className="grid gap-1 py-5"><Link href="/shop" onClick={() => setMenuOpen(false)} className="rounded-xl bg-[#eaf5f6] px-4 py-3 text-sm font-black text-[#12616c]">{isArabic ? "كل المنتجات" : "All products"}</Link>{navItems.map(item => <Link key={item.href} href={item.href} onClick={() => setMenuOpen(false)} className="rounded-xl px-4 py-3 text-sm font-bold text-[#38565d] hover:bg-[#eff7f7]">{isArabic ? item.ar : item.en}</Link>)}</nav><Button onClick={() => { setMenuOpen(false); openCart(); }} className="h-12 w-full rounded-xl bg-[#16717d] hover:bg-[#105d67]"><ShoppingBag />{isArabic ? "فتح سلة الطلب" : "Open request cart"}</Button></div></div> : null}

    <main>{children}</main>
    <footer className="mt-14 bg-[#102f39] text-[#edf8f8]"><div className="raed-container grid gap-9 py-12 sm:grid-cols-2 lg:grid-cols-[1.35fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-3"><img src={resolvedLogoUrl} alt="" className="h-11 w-11 rounded-xl object-cover" /><span className="font-display text-2xl">{isArabic ? "مطبعة الروعة" : "Al Rawaa Printing"}</span></div><p className="mt-4 max-w-md text-sm leading-7 text-[#c6d7d9]">{isArabic ? "مطبوعات وهدايا حسب الطلب تُنفذ بعناية في عجمان وتصل إلى كل الإمارات." : "Made-to-order printed gifts and details, crafted in Ajman and delivered across the UAE."}</p><a href={contact.instagramUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#f2bd66] hover:text-white"><Instagram className="h-4 w-4" />@{contact.instagram.replace(/^@/, "")}</a></div><div><h3 className="font-bold text-[#f2bd66]">{isArabic ? "استكشاف المتجر" : "Explore"}</h3><nav className="mt-4 grid gap-3 text-sm text-[#c6d7d9]"><Link href="/">{isArabic ? "الرئيسية" : "Home"}</Link><Link href="/shop">{isArabic ? "كل المنتجات" : "All products"}</Link>{navItems.slice(0, 3).map(item => <Link key={item.href} href={item.href}>{isArabic ? item.ar : item.en}</Link>)}</nav></div><div><h3 className="font-bold text-[#f2bd66]">{isArabic ? "خدمة الطلب" : "Ordering help"}</h3><div className="mt-4 grid gap-3 text-sm text-[#c6d7d9]"><Link href="/contact">{isArabic ? "سياسة الطلب والتعديل" : "Ordering policy"}</Link><a href={contact.whatsappUrl} target="_blank" rel="noreferrer">{isArabic ? "طلب مخصص عبر واتساب" : "Custom request on WhatsApp"}</a><button onClick={openCart} className="text-start">{isArabic ? "سلة الطلب" : "Request cart"}</button></div></div><div><h3 className="font-bold text-[#f2bd66]">{isArabic ? "تواصل وزيارة" : "Contact & visit"}</h3><div className="mt-4 space-y-3 text-sm text-[#c6d7d9]"><a className="flex items-center gap-2 hover:text-white" href={contact.whatsappUrl} target="_blank" rel="noreferrer"><Phone className="h-4 w-4" />{contact.phone}</a><p className="leading-6">{address}<br />{isArabic ? "توصيل متاح لجميع الإمارات" : "Delivery available across the UAE"}</p></div></div></div><div className="border-t border-white/10 px-5 py-5 text-center text-xs text-[#9db8bc]">© {new Date().getFullYear()} {isArabic ? "مطبعة الروعة. جميع الحقوق محفوظة." : "Al Rawaa Printing. All rights reserved."}</div></footer>
    <Suspense fallback={null}><RequestCartDrawer /></Suspense>
  </div>;
}
