import { esc, trpc } from "./api.js";

const root = document.querySelector("#admin-app");
const state = { active: "dashboard", user: null, dashboard: null, products: [], categories: [], orders: [], content: [] };
const nav = [{ key: "dashboard", ar: "نظرة عامة", en: "Overview" }, { key: "products", ar: "المنتجات", en: "Products" }, { key: "orders", ar: "الطلبات", en: "Requests" }, { key: "contact", ar: "التواصل وواتساب", en: "Contact & WhatsApp" }, { key: "access", ar: "بيانات الدخول", en: "Access" }];
const ar = value => value;
const notice = message => { const element = document.createElement("div"); element.className = "toast"; element.textContent = message; document.body.append(element); setTimeout(() => element.remove(), 3200); };

function layout(content) { root.innerHTML = `<div class="admin-shell" dir="rtl"><aside class="admin-sidebar"><a class="brand" href="/"><img src="/manus-storage/alrawhaa-logo_cfae3a03.webp" alt="Al Rawaa"><span>مطبعة الروعة<small>لوحة التحكم</small></span></a>${nav.map(item => `<button class="${state.active === item.key ? "active" : ""}" data-tab="${item.key}">${item.ar}</button>`).join("")}<button data-logout>تسجيل الخروج</button></aside><main class="admin-main">${content}</main></div>`; }

function login() { root.innerHTML = `<section class="admin-login" dir="rtl"><form class="login-box" id="login"><span class="eyebrow">إدارة مطبعة الروعة</span><h1>تسجيل دخول المدير</h1><p>سجّل الدخول للوصول إلى بيانات المنتجات والطلبات.</p><input class="input" required name="username" autocomplete="username" placeholder="اسم المستخدم"><input class="input" required name="password" type="password" autocomplete="current-password" placeholder="كلمة المرور"><button class="button" type="submit">دخول آمن</button><a class="button secondary" href="/">العودة إلى المتجر</a></form></section>`; }

async function loadDashboard() { state.dashboard = await trpc("store.admin.dashboard"); layout(`<span class="eyebrow">لوحة التحكم</span><h1>مرحبًا ${esc(state.user?.name || "مدير المتجر")}</h1><div class="admin-grid"><article class="stat"><span>المنتجات</span><b>${state.dashboard.products}</b></article><article class="stat"><span>الطلبات</span><b>${state.dashboard.orders}</b></article><article class="stat"><span>طلبات جديدة</span><b>${state.dashboard.newOrders}</b></article><article class="stat"><span>الفئات</span><b>${state.dashboard.categories}</b></article></div><section class="admin-panel"><h2>تشغيل آمن</h2><p>تُدار البيانات من الخادم المحمي. لا تُحفظ أي كلمات مرور أو مفاتيح داخل صفحات HTML أو JavaScript.</p></section>`); }

async function products() { [state.products, state.categories] = await Promise.all([trpc("store.admin.products"), trpc("store.admin.categories")]); const categories = state.categories.map(category => `<option value="${category.id}">${esc(category.titleAr)}</option>`).join(""); const occasions = [["birthday", "أعياد الميلاد"], ["graduation", "حفلات التخرج"], ["wedding", "حفلات الزفاف"], ["newborn", "استقبال مولود"]].map(([value, label]) => `<label><input name="occasionTags" type="checkbox" value="${value}"> ${label}</label>`).join(""); layout(`<div class="section-head"><div><span class="eyebrow">الكتالوج</span><h1>المنتجات</h1></div><button class="button" data-new-product>إضافة منتج</button></div><section class="admin-panel"><div class="form-grid hidden" id="product-form"><input class="input" name="id" type="hidden"><input class="input" name="sortOrder" type="hidden" value="0"><input class="input" required name="slug" placeholder="slug مثل gift-box"><input class="input" required name="titleAr" placeholder="اسم المنتج بالعربية"><input class="input" required name="titleEn" placeholder="Product name in English"><select class="select" name="categoryId"><option value="">بدون فئة</option>${categories}</select><input class="input" name="price" placeholder="السعر أو اتركه فارغًا"><input class="input wide" name="imageUrl" placeholder="رابط صورة التخزين"><textarea class="textarea wide" name="descriptionAr" placeholder="الوصف بالعربية"></textarea><textarea class="textarea wide" name="descriptionEn" placeholder="Description in English"></textarea><fieldset class="wide"><legend>المناسبات المناسبة</legend>${occasions}</fieldset><label><input name="isFeatured" type="checkbox"> منتج مميز</label><label><input name="isAvailable" type="checkbox" checked> متاح</label><button class="button" data-save-product>حفظ المنتج</button></div><table class="table"><thead><tr><th>الصورة</th><th>المنتج</th><th>الفئة</th><th>السعر</th><th></th></tr></thead><tbody>${state.products.map(entry => `<tr><td><img src="${esc(entry.product.imageUrl || "")}" alt=""></td><td><b>${esc(entry.product.titleAr)}</b><br><small>${esc(entry.product.slug)}</small></td><td>${esc(entry.categoryTitleAr || entry.category?.titleAr || "—")}</td><td>${esc(entry.product.price || "حسب الطلب")}</td><td><button class="button secondary" data-edit-product="${entry.product.id}">تعديل</button></td></tr>`).join("")}</tbody></table></section>`); }

function productForm(product = {}) { const form = document.querySelector("#product-form"); form.classList.remove("hidden"); Object.entries(product).forEach(([key, value]) => { const input = form.elements[key]; if (!input) return; if (key === "occasionTags") { const selected = new Set(String(value || "").split(",").filter(Boolean)); form.querySelectorAll('input[name="occasionTags"]').forEach(option => { option.checked = selected.has(option.value); }); } else if (input.type === "checkbox") input.checked = Boolean(value); else input.value = value ?? ""; }); form.scrollIntoView({ behavior: "smooth", block: "start" }); }

async function saveProduct() { const form = document.querySelector("#product-form"); const data = new FormData(form); const payload = { id: data.get("id") ? Number(data.get("id")) : undefined, categoryId: data.get("categoryId") ? Number(data.get("categoryId")) : null, slug: data.get("slug").trim(), titleAr: data.get("titleAr").trim(), titleEn: data.get("titleEn").trim(), descriptionAr: data.get("descriptionAr").trim() || null, descriptionEn: data.get("descriptionEn").trim() || null, price: data.get("price").trim() || null, occasionTags: data.getAll("occasionTags"), imageUrl: data.get("imageUrl").trim() || null, isFeatured: data.get("isFeatured") === "on", isAvailable: data.get("isAvailable") === "on", sortOrder: Number(data.get("sortOrder") || 0) }; await trpc("store.admin.saveProduct", payload, true); notice("تم حفظ المنتج."); products(); }

async function orders() { state.orders = await trpc("store.admin.orders"); layout(`<span class="eyebrow">الطلبات</span><h1>طلبات العملاء</h1><section class="admin-panel"><table class="table"><thead><tr><th>الرقم</th><th>العميل</th><th>المنتج</th><th>الكمية</th><th>الحالة</th></tr></thead><tbody>${state.orders.map(order => `<tr><td>#${order.id}</td><td>${esc(order.customerName)}<br><a href="https://wa.me/${esc(order.customerPhone.replace(/\D/g,""))}" target="_blank" rel="noreferrer">${esc(order.customerPhone)}</a></td><td>${esc(order.productTitle || "طلب مخصص")}</td><td>${order.quantity}</td><td><select class="select" data-order-status="${order.id}">${["new","contacted","confirmed","completed","cancelled"].map(status => `<option value="${status}" ${status === order.status ? "selected" : ""}>${status}</option>`).join("")}</select></td></tr>`).join("")}</tbody></table></section>`); }

async function contact() { state.content = await trpc("store.admin.content"); const values = Object.fromEntries(state.content.map(item => [item.contentKey, item.valueAr || item.valueEn || ""])); const field = (key, label, hint = "") => `<label class="wide"><b>${label}</b><input class="input" name="${key}" value="${esc(values[key] || "")}" placeholder="${esc(hint)}"></label>`; layout(`<span class="eyebrow">التواصل</span><h1>روابط واتساب وبيانات التواصل</h1><form class="admin-panel form-grid" id="contact-form">${field("contact_phone", "رقم الهاتف")}${field("contact_whatsapp", "رقم واتساب الدولي", "9715...")}${field("contact_whatsapp_link", "رابط واتساب مباشر (اختياري)", "https://wa.me/971...")}${field("contact_whatsapp_message_ar", "رسالة واتساب افتراضية بالعربية")}${field("contact_whatsapp_message_en", "رسالة واتساب افتراضية بالإنجليزية")}${field("contact_address_ar", "العنوان بالعربية")}${field("contact_address_en", "العنوان بالإنجليزية")}${field("contact_instagram", "اسم مستخدم Instagram")}<button class="button wide" type="submit">حفظ إعدادات التواصل</button></form>`); }

async function saveContact(form) { const fields = ["contact_phone","contact_whatsapp","contact_whatsapp_link","contact_whatsapp_message_ar","contact_whatsapp_message_en","contact_address_ar","contact_address_en","contact_instagram"]; await Promise.all(fields.map(key => trpc("store.admin.saveContent", { contentKey: key, valueAr: form.elements[key].value.trim() || null, valueEn: form.elements[key].value.trim() || null }, true))); notice("تم حفظ إعدادات التواصل وواتساب."); }

async function access() { const profile = await trpc("auth.localProfile"); layout(`<span class="eyebrow">الحماية</span><h1>بيانات دخول المدير</h1><section class="admin-panel"><p>المستخدم الحالي: <b>${esc(profile.username)}</b></p><form class="form-grid" id="credentials"><input class="input wide" name="currentPassword" type="password" required placeholder="كلمة المرور الحالية"><input class="input" name="username" required value="${esc(profile.username)}" placeholder="اسم المستخدم"><input class="input" name="password" type="password" required minlength="8" placeholder="كلمة مرور جديدة (8 أحرف على الأقل)"><button class="button wide" type="submit">تحديث بيانات الدخول</button></form></section>`); }

async function show() { if (state.active === "dashboard") return loadDashboard(); if (state.active === "products") return products(); if (state.active === "orders") return orders(); if (state.active === "contact") return contact(); return access(); }

document.addEventListener("click", async event => { const target = event.target.closest("[data-tab],[data-logout],[data-new-product],[data-edit-product],[data-save-product]"); if (!target) return; try { if (target.dataset.tab) { state.active = target.dataset.tab; return show(); } if (target.hasAttribute("data-logout")) { await trpc("auth.adminLogout", undefined, true); return init(); } if (target.hasAttribute("data-new-product")) return productForm({ isAvailable: true }); if (target.dataset.editProduct) { const entry = state.products.find(item => item.product.id === Number(target.dataset.editProduct)); return productForm(entry?.product); } if (target.hasAttribute("data-save-product")) return saveProduct(); } catch (error) { notice(error.message); } });
document.addEventListener("change", event => { const id = event.target.dataset.orderStatus; if (id) trpc("store.admin.updateOrderStatus", { id: Number(id), status: event.target.value }, true).then(() => notice("تم تحديث حالة الطلب.")).catch(error => notice(error.message)); });
document.addEventListener("submit", event => { if (event.target.id === "login") { event.preventDefault(); const form = event.target; trpc("auth.localLogin", { username: form.username.value, password: form.password.value }, true).then(init).catch(error => notice(error.message)); } if (event.target.id === "contact-form") { event.preventDefault(); saveContact(event.target).catch(error => notice(error.message)); } if (event.target.id === "credentials") { event.preventDefault(); const form = event.target; trpc("auth.updateLocalCredentials", { currentPassword: form.currentPassword.value, username: form.username.value, password: form.password.value }, true).then(() => { notice("تم تحديث بيانات الدخول."); form.reset(); }).catch(error => notice(error.message)); } });

async function init() { try { state.user = await trpc("auth.adminMe"); if (!state.user) return login(); await show(); } catch { login(); } }
init();
